### ISSUE TITLE
Can't Import LGAs

### ISSUE THREAD

**Issue by aminua** [aminua/Odoo-HR-customization#3]
Lekan,

I have the attached file with the names of LGAs.

I could not import it thru Odoo.

I can import the states without problem,
[States and LGAs.xlsx](https://github.com/aminua/Odoo-HR-customization/files/1762310/States.and.LGAs.xlsx)

**Comment by obabawale** [comment]
Sir,
Based on our discussions, i have downloaded the file you attached and will try to do the import from my end. I will look for the list of constituencies too and forward it to you if I find it.

Thanks

**Comment by obabawale** [comment]
Sir, 
This has been fixed.
We can consider this issue closed.

Sincerely,
Olalekan

**Comment by obabawale** [comment]
I consider this issue resolved, hence closed.
